CREATE OR REPLACE VIEW V_SERVANT_YEARS_INFO
AS
SELECT 
P.LEVEL_CODE || P.LEADER_CODE AS POST_ID ,
CASE 
WHEN P.LEVEL_NAME || LEADER_NAME = '省部级正职领导职务' THEN '省部级正职'
WHEN P.LEVEL_NAME || LEADER_NAME = '省部级副职领导职务' THEN '省部级副职'
WHEN P.LEVEL_NAME || LEADER_NAME = '办事员级非领导职务' THEN '办事员'
WHEN P.LEVEL_NAME || LEADER_NAME = '科员级非领导职务' THEN '科员' 
WHEN P.LEVEL_NAME || LEADER_NAME = '未定职公务员非领导职务' THEN '使用期人员' ELSE 
P.LEVEL_NAME || LEADER_NAME  END AS POST_NAME 
,CASE WHEN S.YEARS <= 20 THEN COUNT(S.ID) ELSE 0 END Y20
,CASE WHEN S.YEARS = 21 THEN COUNT(S.ID) ELSE 0 END Y21 
,CASE WHEN S.YEARS = 22 THEN COUNT(S.ID) ELSE 0 END Y22
,CASE WHEN S.YEARS = 23 THEN COUNT(S.ID) ELSE 0 END Y23 
,CASE WHEN S.YEARS = 24 THEN COUNT(S.ID) ELSE 0 END Y24 
,CASE WHEN S.YEARS = 25 THEN COUNT(S.ID) ELSE 0 END Y25 
,CASE WHEN S.YEARS = 26 THEN COUNT(S.ID) ELSE 0 END Y26 
,CASE WHEN S.YEARS = 27 THEN COUNT(S.ID) ELSE 0 END Y27 
,CASE WHEN S.YEARS = 28 THEN COUNT(S.ID) ELSE 0 END Y28 
,CASE WHEN S.YEARS = 29 THEN COUNT(S.ID) ELSE 0 END Y29 
,CASE WHEN S.YEARS = 30 THEN COUNT(S.ID) ELSE 0 END Y30 
,CASE WHEN S.YEARS = 31 THEN COUNT(S.ID) ELSE 0 END Y31 
,CASE WHEN S.YEARS = 32 THEN COUNT(S.ID) ELSE 0 END Y32 
,CASE WHEN S.YEARS = 33 THEN COUNT(S.ID) ELSE 0 END Y33 
,CASE WHEN S.YEARS = 34 THEN COUNT(S.ID) ELSE 0 END Y34 
,CASE WHEN S.YEARS = 35 THEN COUNT(S.ID) ELSE 0 END Y35 
,CASE WHEN S.YEARS = 36 THEN COUNT(S.ID) ELSE 0 END Y36 
,CASE WHEN S.YEARS = 37 THEN COUNT(S.ID) ELSE 0 END Y37 
,CASE WHEN S.YEARS = 38 THEN COUNT(S.ID) ELSE 0 END Y38 
,CASE WHEN S.YEARS = 39 THEN COUNT(S.ID) ELSE 0 END Y39 
,CASE WHEN S.YEARS = 40 THEN COUNT(S.ID) ELSE 0 END Y40 
,CASE WHEN S.YEARS = 41 THEN COUNT(S.ID) ELSE 0 END Y41 
,CASE WHEN S.YEARS = 42 THEN COUNT(S.ID) ELSE 0 END Y42 
,CASE WHEN S.YEARS = 43 THEN COUNT(S.ID) ELSE 0 END Y43 
,CASE WHEN S.YEARS = 44 THEN COUNT(S.ID) ELSE 0 END Y44 
,CASE WHEN S.YEARS = 45 THEN COUNT(S.ID) ELSE 0 END Y45 
,CASE WHEN S.YEARS = 46 THEN COUNT(S.ID) ELSE 0 END Y46 
,CASE WHEN S.YEARS = 47 THEN COUNT(S.ID) ELSE 0 END Y47 
,CASE WHEN S.YEARS = 48 THEN COUNT(S.ID) ELSE 0 END Y48 
,CASE WHEN S.YEARS = 49 THEN COUNT(S.ID) ELSE 0 END Y49 
,CASE WHEN S.YEARS = 50 THEN COUNT(S.ID) ELSE 0 END Y50 
,CASE WHEN S.YEARS = 51 THEN COUNT(S.ID) ELSE 0 END Y51 
,CASE WHEN S.YEARS = 52 THEN COUNT(S.ID) ELSE 0 END Y52 
,CASE WHEN S.YEARS = 53 THEN COUNT(S.ID) ELSE 0 END Y53 
,CASE WHEN S.YEARS = 54 THEN COUNT(S.ID) ELSE 0 END Y54 
,CASE WHEN S.YEARS = 55 THEN COUNT(S.ID) ELSE 0 END Y55 
,CASE WHEN S.YEARS = 56 THEN COUNT(S.ID) ELSE 0 END Y56 
,CASE WHEN S.YEARS = 57 THEN COUNT(S.ID) ELSE 0 END Y57 
,CASE WHEN S.YEARS = 58 THEN COUNT(S.ID) ELSE 0 END Y58 
,CASE WHEN S.YEARS = 59 THEN COUNT(S.ID) ELSE 0 END Y59 
,CASE WHEN S.YEARS = 60 THEN COUNT(S.ID) ELSE 0 END Y60 
,CASE WHEN S.YEARS = 61 THEN COUNT(S.ID) ELSE 0 END Y61 
,CASE WHEN S.YEARS = 62 THEN COUNT(S.ID) ELSE 0 END Y62 
,CASE WHEN S.YEARS = 63 THEN COUNT(S.ID) ELSE 0 END Y63 
,CASE WHEN S.YEARS = 64 THEN COUNT(S.ID) ELSE 0 END Y64 
,CASE WHEN S.YEARS = 65 THEN COUNT(S.ID) ELSE 0 END Y65 
,CASE WHEN S.YEARS >= 66 THEN COUNT(S.ID) ELSE 0 END Y66 
FROM V_SERVANT_POST_LEVEL_INFO P
LEFT JOIN V_SERVANT_BASIC_INFO S ON S.JL_CODE = P.LEVEL_CODE AND S.IS_LEADER_POST_CODE = P.LEADER_CODE 
GROUP BY P.LEVEL_CODE ,P.LEADER_CODE ,P.LEVEL_NAME,P.LEADER_NAME,S.YEARS


