CREATE OR REPLACE VIEW V_SERVANT_BASIC_INFO
AS
SELECT DISTINCT 
--主键ID
A.ID,
--公务员姓名
A.A01001 AS NAME,
--身份证ID
A.A01084 AS ID_NUMBER,
--所在组织ID
A.DEPARTID AS DEPART_ID,
--所在组织名称
N.NAME AS DEPART_NAME,
--性别代码
SX.CODE AS SEX_CODE,
--性别
SX.NAME AS SEX_NAME,
--民族代码
NA.CODE AS NATION_CODE,
--民族
NA.NAME AS NATION_NAME,
--政治面貌代码
PO.CODE AS PO_CODE,
PO.NAME AS PO_NAME,
--职级代码
CASE WHEN A5.JL_CODE IS NULL THEN 'N/A' ELSE A5.JL_CODE END AS JL_CODE,
--职级
CASE WHEN A5.JL_NAME IS NULL THEN 'N/A' ELSE A5.JL_NAME END AS JL_NAME,
--职务代码
CASE WHEN A2.POST_CODE IS NULL THEN 'N/A' ELSE A2.POST_CODE END AS POST_CODE,
--职务
CASE WHEN A2.POST_NAME IS NULL THEN 'N/A' ELSE A2.POST_NAME END AS POST_NAME,
--是否为领导职务代码
CASE WHEN A2.IS_LEADER_POST_CODE IS NULL THEN 'N/A' ELSE A2.IS_LEADER_POST_CODE END AS IS_LEADER_POST_CODE,
--是否为领导职务
CASE WHEN A2.IS_LEADER_POST_NAME  IS NULL THEN 'N/A' ELSE A2.IS_LEADER_POST_NAME END AS IS_LEADER_POST_NAME,
--任职年限
CASE WHEN A2.A02006 IS NULL THEN 'N/A' ELSE (EXTRACT(MONTH FROM SYSDATE) - EXTRACT(MONTH FROM A2.A02006))/12 END AS POST_YEARS,
--学历代码
CASE WHEN A8.EDUCATION_CODE IS NULL THEN 'N/A' ELSE A8.EDUCATION_CODE END AS EDUCATION_CODE,
--学历
CASE WHEN A8.EDUCATION_NAME IS NULL THEN 'N/A' ELSE A8.EDUCATION_NAME END AS EDUCATION_NAME,
--学位代码
CASE WHEN A9.DEGREE_CODE IS NULL THEN 'N/A' ELSE A9.DEGREE_CODE END AS DEGREE_CODE,
--学位
CASE WHEN A9.DEGREE_NAME IS NULL THEN 'N/A' ELSE A9.DEGREE_NAME END AS DEGREE_NAME,
--年龄
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM A.A01007) AS YEARS,
--任职状态代码
IH.CODE AS IS_HOLD_CODE,
--任职状态
IH.NAME AS IS_HOLD_NAME
FROM 
--公务员主表
A01 A 
--关联性别字典
JOIN CF_CODE_INFO SX ON SX.ID = A.A01004 AND  SX.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_2261_1_2003') 
--关联民族字典
JOIN CF_CODE_INFO NA ON NA.ID = A.A01017 AND  NA.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_3304_1991')
--关联任职状态字典
JOIN CF_CODE_INFO IH ON IH.ID = A.A01063  AND IH.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM200') AND IH.CODE = '1'
--关联政治面貌
JOIN CF_CODE_INFO PO ON PO.ID = A.SH_A2205  AND PO.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_4762_1984')

--关联职级信息
--LEFT JOIN CF_CODE_INFO JL ON JL.ID = A.SH_A0192E AND  JL.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_12407_2008') AND JL.CODE LIKE '1%' AND JL.CODE != '1'
--关联职务
--LEFT JOIN CF_CODE_INFO PT ON PT.ID = A.SH_A0705 AND  PT.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_12403_1990') 
--关联是否为领导职务
--LEFT JOIN CF_CODE_INFO LP ON LP.ID = A.SH_A0702 AND  LP.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM049')

--职务表
LEFT JOIN (
SELECT A2.SERVANT_ID,PT.CODE AS POST_CODE,PT.NAME AS POST_NAME,LP.CODE AS IS_LEADER_POST_CODE,LP.NAME AS IS_LEADER_POST_NAME,A02006  
FROM A02 A2 
--关联职务字典
JOIN CF_CODE_INFO PT ON PT.ID = A2.A02016B AND  PT.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_12403_1990') 
--关联最高职务字典
JOIN CF_CODE_INFO TP ON TP.ID = A2.SH_S0163_1 AND  TP.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM215')  AND TP.CODE = '1'
--关联任职状态字典
JOIN CF_CODE_INFO IO ON IO.ID = A2.SH_S0163 AND  IO.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM215')  AND IO.CODE = '1'
--关联是领导任职字典
JOIN CF_CODE_INFO LP ON LP.ID = A2.A02008 AND  LP.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM049')
) A2 ON A2.SERVANT_ID = A.ID


--职级表
LEFT JOIN (
SELECT A5.SERVANT_ID,JL.CODE AS JL_CODE,JL.NAME AS JL_NAME FROM A05 A5 
--关联职级字典
JOIN CF_CODE_INFO JL ON JL.ID = A5.A05002B AND  JL.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_12407_2008') AND CODE LIKE '1%' AND CODE != '1'
--关联任职状态字典
JOIN CF_CODE_INFO JN ON JN.ID = A5.A05024 AND  JN.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM215')  AND JN.CODE = '1' 
) A5 ON A5.SERVANT_ID = A.ID


--学历表
LEFT JOIN (
SELECT A8.SERVANT_ID,EP.CODE AS EDUCATION_CODE,EP.NAME AS EDUCATION_NAME FROM  A08 A8 
--关联学历字典
JOIN CF_CODE_INFO EP ON EP.ID = A8.A08002B AND  EP.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_4658_2006')
--关联是否为最高学历代码
JOIN CF_CODE_INFO TE ON TE.ID = A8.A08034 AND  TE.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM215')  AND TE.CODE = '1'
) A8 ON A8.SERVANT_ID = A.ID

--学位表
LEFT JOIN (
SELECT A9.SERVANT_ID,DR.CODE AS DEGREE_CODE,DR.NAME AS DEGREE_NAME FROM A09 A9 
--关联学位字典
JOIN CF_CODE_INFO DR ON DR.ID = A9.A09001B AND  DR.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_6864_2003')
--关联是否为最高学位代码
JOIN CF_CODE_INFO TD ON TD.ID = A9.A09014 AND  TD.TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM215')  AND TD.CODE = '1'
) A9 ON A9.SERVANT_ID = A.ID
--关联公务员所在组织
JOIN CS_ORGAN_NODE N ON A.DEPARTID = N.ID
WHERE A.REMOVED = 'N';