CREATE OR REPLACE VIEW V_SERVANT_POST_LEVEL_INFO
AS
SELECT * FROM (
	SELECT 
	LEVEL_CODE || LEADER_CODE AS ID,  
	LEVEL_CODE,
	LEVEL_NAME,
	LEADER_CODE,
	LEADER_NAME 
	FROM 
	(
		SELECT CODE AS LEVEL_CODE,NAME AS LEVEL_NAME 
		FROM CF_CODE_INFO 
		WHERE TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'GBT_12407_2008') AND CODE LIKE '1%' AND CODE != '1' AND CODE != '101' AND CODE != '102'
	)
	CROSS JOIN 
	(
		SELECT CODE AS LEADER_CODE,NAME AS LEADER_NAME 
		FROM CF_CODE_INFO WHERE TYPE_ID = (SELECT ID FROM CF_CODE_TYPE WHERE CODE = 'DM049') AND LENGTH(CODE) = 1 AND CODE != '9'
	)
) WHERE ID != '1509' AND ID != '1501' AND ID != '1609' AND ID != '1601' AND ID != '1991' AND ID != '1999' AND ID != '1112' AND ID != '1122'
