CREATE OR REPLACE VIEW V_SERVANT_INFO
AS
SELECT 
P.LEVEL_CODE || P.LEADER_CODE AS POST_ID ,
CASE 
WHEN P.LEVEL_NAME || LEADER_NAME = '省部级正职领导职务' THEN '省部级正职'
WHEN P.LEVEL_NAME || LEADER_NAME = '省部级副职领导职务' THEN '省部级副职'
WHEN P.LEVEL_NAME || LEADER_NAME = '办事员级非领导职务' THEN '办事员'
WHEN P.LEVEL_NAME || LEADER_NAME = '科员级非领导职务' THEN '科员' 
WHEN P.LEVEL_NAME || LEADER_NAME = '未定职公务员非领导职务' THEN '试用期人员' ELSE 
P.LEVEL_NAME || LEADER_NAME  END AS POST_NAME 
--性别
,CASE WHEN S.SEX_CODE = '2' THEN COUNT(S.ID) ELSE 0 END SEX
--民族
,CASE WHEN S.NATION_CODE != '01' THEN COUNT(S.ID) ELSE 0 END NATION
--政治面貌
,CASE WHEN S.PO_CODE = '01' THEN COUNT(S.ID) ELSE 0 END POLITICS
--博士
,CASE WHEN S.DEGREE_CODE LIKE '1%' OR S.DEGREE_CODE LIKE '2%' THEN COUNT(S.ID) ELSE 0 END DEGREE2
--硕士
,CASE WHEN S.DEGREE_CODE LIKE '3%' THEN COUNT(S.ID) ELSE 0 END DEGREE3
--学士
,CASE WHEN S.DEGREE_CODE LIKE '4%' THEN COUNT(S.ID) ELSE 0 END DEGREE4
--研究生毕业
,CASE WHEN S.EDUCATION_CODE LIKE '1%' THEN COUNT(S.ID) ELSE 0 END EDUCATION1
--本科毕业
,CASE WHEN S.EDUCATION_CODE LIKE '2%' THEN COUNT(S.ID) ELSE 0 END EDUCATION2
--专科毕业
,CASE WHEN S.EDUCATION_CODE LIKE '3%' THEN COUNT(S.ID) ELSE 0 END EDUCATION3
--其他毕业
,CASE WHEN S.EDUCATION_CODE LIKE '1%' AND S.EDUCATION_CODE LIKE '2%' AND S.EDUCATION_CODE LIKE '2%' THEN COUNT(S.ID) ELSE 0 END EDUCATION4
--兼任下级领导职务
, 0 AS SUB_LEADER
--小于两年
,CASE WHEN S.POST_YEARS < 2 THEN COUNT(S.ID) ELSE 0 END YEAR1
--大于2年并小于3年
,CASE WHEN S.POST_YEARS >= 2 AND S.POST_YEARS < 3 THEN COUNT(S.ID) ELSE 0 END YEAR2
--大于3年并小于4年
,CASE WHEN S.POST_YEARS >= 3 AND S.POST_YEARS < 4 THEN COUNT(S.ID) ELSE 0 END YEAR3
--大于4年并小于5年
,CASE WHEN S.POST_YEARS >= 4 AND S.POST_YEARS < 5 THEN COUNT(S.ID) ELSE 0 END YEAR4
--大于5年并小于6年
,CASE WHEN S.POST_YEARS >= 5 AND S.POST_YEARS < 6 THEN COUNT(S.ID) ELSE 0 END YEAR5
--大于6年并小于7年
,CASE WHEN S.POST_YEARS >= 6 AND S.POST_YEARS < 7 THEN COUNT(S.ID) ELSE 0 END YEAR6
--大于8年并小于12年
,CASE WHEN S.POST_YEARS >= 8 AND S.POST_YEARS < 12 THEN COUNT(S.ID) ELSE 0 END YEAR7
--大于12年并小于15年
,CASE WHEN S.POST_YEARS >= 12 AND S.POST_YEARS <15 THEN COUNT(S.ID) ELSE 0 END YEAR8
--大于15年
,CASE WHEN S.POST_YEARS >= 15  THEN COUNT(S.ID) ELSE 0 END YEAR9
FROM V_SERVANT_POST_LEVEL_INFO P
LEFT JOIN V_SERVANT_BASIC_INFO S ON S.JL_CODE = P.LEVEL_CODE AND S.IS_LEADER_POST_CODE = P.LEADER_CODE 
GROUP BY P.LEVEL_CODE ,P.LEADER_CODE ,P.LEVEL_NAME,P.LEADER_NAME,S.SEX_CODE,S.NATION_CODE,S.PO_CODE,S.DEGREE_CODE,S.EDUCATION_CODE,S.POST_YEARS